language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 hello.c -o hello
  - ./hello
  - gcov hello.c
  -coveralls:report


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://coveralls.io/bash)
